### ISSUE TITLE
Build failure: si2168.h: No such file or directory

### ISSUE THREAD

**Issue by HenkPoley** [AlexanderS/tbsecp3-driver#3] opened 2020-04-25 13:51 UTC
For that matter I know the file exists: `/usr/src/linux-headers-5.3.0-46-generic/include/config/dvb/si2168.h` just not in the place it is looking at. Does building require anything extra, apart from a `git clone` ?

```
tbsecp3-driver$ LANG=C make
make -C /lib/modules/`uname -r`/build M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-5.3.0-46-generic'
  CC [M]  /mnt/store/TBS6590/tbsecp3-driver/tbsecp3/tbsecp3-dvb.o
/mnt/store/TBS6590/tbsecp3-driver/tbsecp3/tbsecp3-dvb.c:23:10: fatal error: drivers/media/dvb-frontends/si2168.h: No such file or directory
 #include <drivers/media/dvb-frontends/si2168.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
scripts/Makefile.build:288: recipe for target '/mnt/store/TBS6590/tbsecp3-driver/tbsecp3/tbsecp3-dvb.o' failed
make[2]: *** [/mnt/store/TBS6590/tbsecp3-driver/tbsecp3/tbsecp3-dvb.o] Error 1
Makefile:1655: recipe for target '_module_/mnt/store/TBS6590/tbsecp3-driver' failed
make[1]: *** [_module_/mnt/store/TBS6590/tbsecp3-driver] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.3.0-46-generic'
Makefile:4: recipe for target 'default' failed
make: *** [default] Error 2
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

```
$ uname -a
Linux Oehoe 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Delitants** [comment] 2020-05-08 19:25
I dunno what is this guy uploaded here, but it's not compiling..

`/tbsecp3-driver/tbsecp3/tbsecp3.h:31:10: fatal error: media/dmxdev.h: No such file or directory
 #include <media/dmxdev.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.`

**Comment by HenkPoley** [comment] 2020-05-09 04:25
I think it builds with particular Arch distro kernels.

**Comment by Delitants** [comment] 2020-05-16 08:12
I guess you still need to put all this stuff into https://github.com/tbsdtv/linux_media and compile there, which doesn't make any sense, because he says a media tree not required, which is not true.

**Comment by moreiraedx** [comment] 2020-08-25 02:30
Anyone fixed the Ubuntu 18 build issue?

**Comment by AlexanderS** [comment] 2021-02-16 17:41
I think, this was a duplicate of #2. The build should be fixed now. Please reopen if you have still have issues.

**Closed as completed by AlexanderS** 2021-02-16 17:41 UTC

**Comment by HenkPoley** [comment] 2022-03-10 18:48
I've ran `make` successful on Ubuntu 18.04.6. I haven't tried installing and using it. But it's at least an improvement 😉
